
String galaxyText = "Galaxy is the inter-Hall cultural championship and also one of the flagship events that are organised by the Media and Cultural Council. It is a series of cultural competitions meant to unleash the cultural rigour of the under-graduate students; and is spread (usually) over a period of 5-7 days in the even semester of every academic year.Galaxy is looked up with a lot of liveliness and enthusiasm on behalf of the undergraduates, who see it as a way to establish the cultural flair of their halls and “prove their worth and dominance” amongst the other halls. Performing their best in the Galaxy is a want for the fresher undergraduates and they fight tooth and nail for all events to ensure that their pools stay the closest to the Galaxy Championship Trophy.Galaxy conducts a plethora of competitions for all existing clubs and some more miscellaneous events. The proper conduction of the Galaxy events require all Halls-of-Residence to be split into 5 pools: Peshwas, Aryans, Shauryas, Kshatriyas and Nawabs. These pools comprises of all the halls including UGs and PGs in the institute developing a bond and spirit of team work between them. The Pool which has the highest points at the end of the events gets the Galaxy Championship Trophy. Each pool is piloted by a team of people headed by the one known as \“Pool Captain\” and guide their respective pools";
String freshersText = "When a person enters a new university or institution, he/she is likely to face a whirlwind of emotions. We at IIT Kanpur completely understand these emotional pangs and aim to help our freshers in the best way possible.For this, the Media and Cultural Council organises a Freshers’ Night gala within a month of them joining the institute, so as to help them in transforming these negative feelings and emotions into something that is more productive and leads to their erudition.The Freshers’ Nite also marks the very initial association between the freshers and the club. This event plays a chief role in establishing and uniting the freshers with the clubs that they are interested in. It furnishes a window of opportunity for the freshmen to interact with the sophomores and other seniors to enhance their skills. It provides budding artists with a perfect platform to exhibit their flair. The gala event includes performances of all the clubs that come under the council. In fact, it is the freshers themselves who are the charioteers of the event. The Freshers’ Nite provides the perfect opportunity for the new students to feel more confident, and exposure to the various clubs and societies that the council endorses.The event is highly applauded for the way it aims to blend the freshers with their seniors, and also amongst themselves. It is reviewed to be a highly holistic experience, both by the audience as well as the freshmen. The event is received by a highly enthusiastic audience; and has an astonishingly wide reach";
String impressionText = "The daily routine of most of the post-graduate students at IIT Kanpur is characterised by heavy coursework, labwork, thesis-preparation and projects. Impressions is an exclusive series of events which is organised for the post-graduate students by the Media and Cultural Council of IIT Kanpur, which offers them a platform to showcase their latent talents in the field of arts and culture, as well as act like a stress-buster.The Media and Cultural Council conducted Impressions’20 after a gap of one year. The theme was as exhilarating as it could have been- A Sensational Reverberance. This year, the major attractions of the event were Verve (glamour walk), Footloose (dance fiesta), Dhvani (music gala night), Kalakriti (art exhibition), Abhivyaksti (drama performance), the poetry night Alfaaz, as well as the highly awaited Prom Night, all of them witnessing a massive turnout from the audience. The online photography contest Shutterbug also witnessed popular participation. All in all Impressions is a highly rejuvenating experience for the post-graduate students.";
String montageText = "Films, photography, arts and literature are all about capturing the essence of human lives. They expand our horizons of thinking- introducing us to a whole new world which we had never imagined before and giving us a truthful reflection of our own selves. Montage- the festival that cherishes films, photography, literature and arts; is one of the most illustrious events that are organized by the Media and Cultural council. The cultural festival, Montage, is not just a celebration, but an experience. One of the Council’s major achievements this year has been the remarkable execution and conduction of the cultural event Montage. This year, Montage had just as buoyant a theme as its vision was. It won’t be wrong to say that the theme was pretty jazzy- “Kaleidoscope”.At Montage, it’s believed that the arts, literature and photographs that we revere, are a reflection of our own lives. Montage is about storytelling- from fictional tales to real-life accounts of real people. It is all about celebrating the arts and there is no better way to celebrate arts than celebrating the great artists and the people who produce those arts.The festival aims to not only broaden and enhance the way the audience views the various arts; but also introduce them to the wonders of artistic media. Apart from showcasing some of the Indian Cinema, a major feature of the festival is the informal discussions by some of the most talented personalities of the Indian films and media industry. These discussions are meant to provide the audience with an insider’s perspective towards the formal arts; that would help them to appreciate and understand as to why the arts are an important part of our lives.Montage features a large number of movie screenings of various genres, which never fail to garner an enthusiastic audience and critics. The book fairs organized under Montage gathered good reviews and were applauded for their extensive collection. Kavi Sammelan event received a huge audience, most of them being classical Hindi enthusiasts. We also organized lectures and workshops by various Featured artists who magnificently passed on their artistic rigour and experiences to their audience.";
String cultText = "The year 2019 saw the Inter-IIT Cultural Meet being organised at IIT Bombay. While IIT Kharagpur seized the Overall Championship; IIT Kanpur gave a good competition and secured the coveted fifth position. This year, the Meet consisted of competitions on Dance, Dramatics, Films, Music, Literary Arts, Speaking arts, Fine arts, Design and Digital Arts, Fashion as well as Miscellaneous Arts.Our Dance team “KOS” secured the 1st position in Group Dance, was the 1st runner-up in the street battle, and was declared the Overall Dance Champion. The Dramatics Club also outperformed itself by securing the 1st position in the Street Play Competition and the 2nd position in the Mime Competition. The English Literary Society secured the overall 1st position in literary events. Besides bagging four golds and one silver in Word Games and JAM, the club made everyone proud with their splendid performances in Creative Writing and Slam Poetry securing sixth and seventh positions in the events respectively.The Photography Club won laurels for the campus by securing the 1st position in the Street Photography Competition, with the Fine Arts Club securing the overall 4th position for IIT Kanpur. The Music Club surpassed its previous performances by saving the 4th position for itself in the Band Competition.";
String subGalaxy = "\"Nothing is as contagious as enthusiasm.\"";
String subFreshers= "\“Every great artist started as an amateur.\”";
String subImpression = "\“Culture is coded wisdom.\”";
String subMontage = "\"Art is an effort to create, beside a real world, a more humane world.\"";
String subCult = "\“Culture does not make people. People make culture.\”";
late String userName;





